# Analysis of data from different sources

List of sources:

1. [TradingEconomics](https://github.com/tradingeconomics/tradingeconomics/tree/master/python).
2. [Financial Modeling Prep API](https://financialmodelingprep.com/developer/docs/)

## 1. TradingEconomics[$^1$](http://docs.tradingeconomics.com/#historical27)

In [2]:
# pip install -i https://pypi.python.org/pypi tradingeconomics

To obtain a Key we need to contact `support@tradingeconomics.com`:

```
$ bash -c 'curl -i "https://api.tradingeconomics.com/country/united%20states/" -H "Authorization: Client guest:guest"'

HTTP/2 401
date: Tue, 03 Nov 2020 11:58:08 GMT
content-type: text/plain; charset=utf-8
content-length: 83
cache-control: no-cache
pragma: no-cache
expires: -1
server: Microsoft-IIS/10.0
access-control-allow-credentials: true
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET

You must provide a valid authorization. Please contact support@tradingeconomics.com
```

However, we can play with the demo for their API - this has some limitations:

In [1]:
import tradingeconomics as te

# te.login("Your_Key:Your_Secret")
te.login()

'You are logged in as a guest:guest'

In [2]:
# To get List of Indicators by Country:
te.getIndicatorData(country=['united states', 'china'], output_type='df')

,Country,Category,Title,LatestValue,LatestValueDate,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,United States,ADP Employment Change,United States ADP Employment Change,749.00,2020-09-30T00:00:00,"Automatic Data Processing, Inc.",Thousand,/united-states/adp-employment-change,Labour,SA,Monthly,UNITEDSTAADPEMPCHA,2014-04-30T13:57:00,481.00,2020-08-31T00:00:00
1,United States,API Crude Imports,United States API Crude Imports,0.44,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-crude-imports,Business,,Weekly,UNITEDSTAAPICRUIMP,2020-07-20T10:54:00,0.07,2020-10-16T00:00:00
2,United States,API Crude Oil Stock Change,United States API Crude Oil Stock Change,4.58,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-crude-oil-stock-change,Business,,Weekly,APICRUDEOIL,2017-11-28T15:21:00,0.58,2020-10-16T00:00:00
3,United States,API Crude Runs,United States API Crude Runs,0.18,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-crude-runs,Business,,Weekly,UNITEDSTAAPICRURUN,2020-07-20T11:02:00,-0.20,2020-10-16T00:00:00
4,United States,API Cushing Number,United States API Cushing Number,0.14,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-cushing-number,Business,,Weekly,UNITEDSTAAPICUSNUM,2020-07-20T11:07:00,1.17,2020-10-16T00:00:00
5,United States,API Distillate Stocks,United States API Distillate Stocks,-5.33,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-distillate-stocks,Business,,Weekly,UNITEDSTAAPIDISSTO,2020-07-20T11:09:00,-5.98,2020-10-16T00:00:00
6,United States,API Gasoline Stocks,United States API Gasoline Stocks,2.25,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-gasoline-stocks,Business,,Weekly,UNITEDSTAAPIGASSTO,2020-07-20T11:11:00,-1.62,2020-10-16T00:00:00
7,United States,API Heating Oil,United States API Heating Oil,-0.40,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-heating-oil,Business,,Weekly,UNITEDSTAAPIHEAOIL,2020-07-20T11:12:00,0.17,2020-10-16T00:00:00
8,United States,API Product Imports,United States API Product Imports,0.39,2020-10-23T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-product-imports,Business,,Weekly,UNITEDSTAAPIPROIMP,2020-07-20T11:14:00,-0.32,2020-10-16T00:00:00
9,United States,Asylum Applications,United States Asylum Applications,7267.00,2018-09-30T00:00:00,United Nations Refugee Agency,Persons,/united-states/asylum-applications,Government,NSA,Monthly,UNITEDSTAASYAPP,2015-09-10T15:49:00,7682.00,2018-08-31T00:00:00

In [33]:
# To get Country/Indicator pair:
te.getIndicatorData(country='united states', indicators='gdp', output_type='df')

,Country,Category,Title,LatestValue,LatestValueDate,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,United States,GDP,United States GDP,21427.7,2019-12-31T00:00:00,World Bank,USD Billion,/united-states/gdp,GDP,Current USD,Yearly,WGDPUS,2014-07-03T16:14:00,20580.22,2018-12-31T00:00:00

In [4]:
# Get historical data:
te.getHistoricalData(country='united kingdom', indicator='gdp', initDate='2015-01-01')

                  0
2015-12-31  2928.59
2016-12-31  2694.28
2017-12-31  2666.23
2018-12-31  2860.67
2019-12-31  2827.11

In [5]:
# Getting historical data by ticker or TE symbol.
te.getHistorical('USURTOT')

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,United States,Unemployment Rate,2019-12-31T00:00:00,3.5,Monthly,USURTOT,2020-02-07T13:30:00
1,United States,Unemployment Rate,2020-01-31T00:00:00,3.6,Monthly,USURTOT,2020-02-07T13:30:00
2,United States,Unemployment Rate,2020-02-29T00:00:00,3.5,Monthly,USURTOT,2020-04-03T12:30:00
3,United States,Unemployment Rate,2020-03-31T00:00:00,4.4,Monthly,USURTOT,2020-05-08T12:30:00
4,United States,Unemployment Rate,2020-04-30T00:00:00,14.7,Monthly,USURTOT,2020-05-08T12:30:00
5,United States,Unemployment Rate,2020-05-31T00:00:00,13.3,Monthly,USURTOT,2020-06-05T12:30:00
6,United States,Unemployment Rate,2020-06-30T00:00:00,11.1,Monthly,USURTOT,2020-07-02T12:31:00
7,United States,Unemployment Rate,2020-07-31T00:00:00,10.2,Monthly,USURTOT,2020-08-07T12:31:00
8,United States,Unemployment Rate,2020-08-31T00:00:00,8.4,Monthly,USURTOT,2020-09-04T12:30:00
9,United States,Unemployment Rate,2020-09-30T00:00:00,7.9,Monthly,USURTOT,2020-10-02T12:30:00

There are some limitations tho:

In [6]:
# Putting country name or indicator name in square brackets will return a dictionary type. For several countries and indicators
te.getHistoricalData(country=['united states', 'china'], indicator=['exports','imports'], 
                     initDate='1990-01-01', endDate='2015-01-01')

HTTPError: HTTP Error 403: No Access to this feature.

In [32]:
# To get Credit Rating data for one country.
te.getRatings(country= 'United states', output_type='df')

,Country,TE,TE_Outlook,SP,SP_Outlook,Moodys,Moodys_Outlook,Fitch,Fitch_Outlook,Outlook,DBRS,DBRS_Outlook
0,United States,98,Stable,AA+,Stable,Aaa,Stable,AAA,Negative,NaN,AAA,Stable

In [7]:
# To get Credit Rating data for several countries.
te.getRatings(country=['United states','Japan'], output_type='df')

,Country,TE,TE_Outlook,SP,SP_Outlook,Moodys,Moodys_Outlook,Fitch,Fitch_Outlook,Outlook,DBRS,DBRS_Outlook
0,Japan,77,Stable,A+,Stable,A1,Stable,A,Negative,NaN,A (high),Stable
1,United States,98,Stable,AA+,Stable,Aaa,Stable,AAA,Negative,NaN,AAA,Stable

In [8]:
# To get Credit Rating historical data for one country.
te.getHistoricalRatings(country= 'United states', output_type='df')

          Country        Date   Agency Rating         Outlook
0   United States   7/31/2020    Fitch    AAA        Negative
1   United States   4/22/2014     DBRS    AAA          Stable
2   United States   3/21/2014    Fitch    AAA          Stable
3   United States  10/15/2013    Fitch    AAA  Negative Watch
4   United States   10/9/2013     DBRS    AAA    Under Review
5   United States   7/18/2013  Moody's    Aaa          Stable
6   United States   6/10/2013      S&P    AA+          Stable
7   United States  11/28/2011    Fitch    AAA        Negative
8   United States    9/8/2011     DBRS    AAA          Stable
9   United States    8/5/2011      S&P    AA+        Negative
10  United States    8/2/2011  Moody's    Aaa        Negative
11  United States   7/14/2011      S&P    AAA  Negative Watch
12  United States   7/13/2011  Moody's    Aaa  Negative Watch
13  United States   4/18/2011      S&P    AAA        Negative
14  United States   9/21/2000    Fitch    AAA          Stable
15  United States    4/1/1996    Fitch    AAA             N/A
16  United States  11/13/1995    Fitch    AAA  Negative Watch
17  United States   8/10/1994    Fitch    AAA             N/A
18  United States    2/5/1949  Moody's    Aaa          Stable

In [34]:
# To get Credit Rating historical data for several countries.
te.getHistoricalRatings(country=['United states','United Kingdom'], output_type='df')[:2]

          Country        Date   Agency Rating   Outlook
0  United Kingdom  10/16/2020  Moody's    Aa3    Stable
1   United States   7/31/2020    Fitch    AAA  Negative

In [35]:
# Without specifying the date a sample of the latest updates will be provided.
# To get latest updates using a starting date.
te.getLatestUpdates(initDate='2018-08-15', output_type='df')

,Country,Category,HistoricalDataSymbol,LastUpdate
0,Australia,Calendar,,2020-01-10T16:08:00
1,Japan,Calendar,,2020-06-26T09:53:00
2,Zimbabwe,Internet Speed,ZWEKBPS,2020-11-02T23:00:00
3,Zimbabwe,Personal Income Tax Rate,ZWEIRSTAX,2020-11-02T23:00:00
4,Zimbabwe,IP Addresses,ZWEIPS,2020-11-02T23:00:00
5,Zimbabwe,Ease of Doing Business,ZWEICBUSEASEXQ,2020-11-02T23:00:00
6,Zimbabwe,Deposit Interest Rate,ZWEFRINRDPST,2020-11-02T23:00:00
7,Zimbabwe,Corporate Tax Rate,ZWECORPTAX,2020-11-02T23:00:00
8,Zimbabwe,Tourist Arrivals,ZIMBABWETOUARR,2020-11-02T23:00:00
9,Zimbabwe,Terrorism Index,ZIMBABWETERIND,2020-11-02T23:00:00

In [11]:
# To get calendar data for a specific country, in data frame format, run:
te.getCalendarId(id= [ 160025,  174108,  160030], output_type=  'df')

TypeError: sequence item 0: expected str instance, int found

#### 1.1. Streamings

They doesn't work as expected, nothing is returned

In [ ]:
import tradingeconomics as te
import json

te.login('guest:guest')

def on_message(ws, message):
  print( json.loads(message) )

te.subscribe('EURUSD:CUR')
te.run(on_message)

You are subscribed to:['EURUSD:CUR']

--- request header ---
GET /?client=guest:guest&app=python&token=20171116 HTTP/1.1
Upgrade: websocket
Host: stream.tradingeconomics.com
Origin: http://stream.tradingeconomics.com
Sec-WebSocket-Key: zTc4h9nE0ud8cy68bpNBhQ==
Sec-WebSocket-Version: 13
Connection: upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: /gtzlW3sMw9+HyItpA0W4tj50tA=
Set-Cookie: SRVNAME=websrv3; path=/
-----------------------
send: b'\x81\xaa\xbc\xf2\xaa\n\xc7\xd0\xdee\xcc\x9b\xc9(\x86\xd2\x88y\xc9\x90\xd9i\xce\x9b\xc8o\x9e\xde\x8a(\xc8\x9d\x880\x9c\xd0\xef_\xee\xa7\xf9N\x86\xb1\xffX\x9e\x8f'

+++ Socket is open!
+++ Subscribe to EURUSD:CUR
{'s': 'EURUSD:CUR', 'i': 'EURUSD', 'pch': 0.55, 'nch': 0.00636, 'bid': 1.17035, 'ask': 1.17035, 'price': 1.17035, 'dt': 1604405936112, 'state': 'open', 'type': 'currency', 'dhigh': 1.17046, 'dlow': 1.1632, 'o': 1.1632, 'prev': 1.16399, 'topic': 'EURUSD'}
{'s': 'EURUSD:CUR', 'i': 'EURUSD', 'pch': 0.55, 'nch': 0.00637, 'bid': 1.17036, 'ask': 1.17036, 'price': 1.17036, 'dt': 1604405936308, 'state': 'open', 'type': 'currency', 'dhigh': 1.17046, 'dlow': 1.1632, 'o': 1.1632, 'prev': 1.16399, 'topic': 'EURUSD'}
{'s': 'EURUSD:CUR', 'i': 'EURUSD', 'pch': 0.54, 'nch': 0.00629, 'bid': 1.17028, 'ask': 1.17028, 'price': 1.17028, 'dt': 1604405939522, 'state': 'open', 'type': 'currency', 'dhigh': 1.17046, 'dlow': 1.1632, 'o': 1.1632, 'prev': 1.16399, 'topic': 'EURUSD'}

send: b'\x88\x82\xc5\x04Hr\xc6\xec'

### closed ### reconnect in 60 seconds

### 1.2 Forecasts

In [12]:
# Forecasted values for specific a country, in this case United States.
te.getForecastData(country='united states', output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date,Frequency,HistoricalDataSymbol
0,United States,ADP Employment Change,749.00,2020-09-30T00:00:00,150.0,150.00,150.00,150.0,2020-12-31T00:00:00,100.00,2021-03-31T00:00:00,200.00,2021-06-30T00:00:00,170.00,2021-09-30T00:00:00,Monthly,UNITEDSTAADPEMPCHA
1,United States,API Crude Oil Stock Change,4.58,2020-10-23T00:00:00,-2.0,2.00,2.00,-2.0,2020-12-31T00:00:00,-2.00,2021-03-31T00:00:00,3.50,2021-06-30T00:00:00,-5.00,2021-09-30T00:00:00,Weekly,APICRUDEOIL
2,United States,Average Hourly Earnings,0.10,2020-09-30T00:00:00,0.1,0.20,0.20,0.1,2020-12-31T00:00:00,0.20,2021-03-31T00:00:00,0.30,2021-06-30T00:00:00,0.40,2021-09-30T00:00:00,Monthly,UNITEDSTAAVEHOUEAR
3,United States,Average Weekly Hours,34.70,2020-09-30T00:00:00,34.5,34.40,34.40,34.5,2020-12-31T00:00:00,34.50,2021-03-31T00:00:00,34.50,2021-06-30T00:00:00,34.40,2021-09-30T00:00:00,Monthly,UNITEDSTAAVEWEEHOU
4,United States,Balance of Trade,-67102.00,2020-08-31T00:00:00,-55000.0,-53000.00,-53000.00,-55000.0,2020-12-31T00:00:00,-47000.00,2021-03-31T00:00:00,-51000.00,2021-06-30T00:00:00,-50000.00,2021-09-30T00:00:00,Monthly,USTBTOT
5,United States,Bank Lending Rate,3.25,2020-09-30T00:00:00,5.5,5.75,3.25,5.5,2020-12-31T00:00:00,3.25,2021-03-31T00:00:00,3.25,2021-06-30T00:00:00,3.25,2021-09-30T00:00:00,Monthly,UNITEDSTABANLENRAT
6,United States,Bankruptcies,22391.00,2020-09-30T00:00:00,35000.0,30000.00,30000.00,35000.0,2020-12-31T00:00:00,35000.00,2021-03-31T00:00:00,24000.00,2021-06-30T00:00:00,22000.00,2021-09-30T00:00:00,Quarterly,UNITEDSTABAN
7,United States,Banks Balance Sheet,20128100.00,2020-10-07T00:00:00,24224722.0,32856716.00,40856716.00,24224722.0,2020-12-31T00:00:00,26082618.00,2021-03-31T00:00:00,28672113.00,2021-06-30T00:00:00,30101100.00,2021-09-30T00:00:00,Weekly,UNITEDSTABANBALSHE
8,United States,Building Permits,1545.00,2020-09-30T00:00:00,1380.0,1200.00,1300.00,1380.0,2020-12-31T00:00:00,1300.00,2021-03-31T00:00:00,1310.00,2021-06-30T00:00:00,1470.00,2021-09-30T00:00:00,Monthly,UNITEDSTABUIPER
9,United States,Business Confidence,59.30,2020-10-31T00:00:00,51.0,53.40,52.40,51.0,2020-12-31T00:00:00,52.00,2021-03-31T00:00:00,53.00,2021-06-30T00:00:00,51.00,2021-09-30T00:00:00,Monthly,NAPMPMI

In [13]:
# Forecasted values for a specific indicator.
te.getForecastData(indicator= 'gdp', output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date,Frequency,HistoricalDataSymbol
0,Afghanistan,GDP,19.10,2019-12-31T00:00:00,18.63,20.46,21.43,18.63,2020-12-31T00:00:00,20.46,2021-03-31T00:00:00,20.46,2021-06-30T00:00:00,20.46,2021-09-30T00:00:00,Yearly,AFGSTANGDP
1,Albania,GDP,15.28,2019-12-31T00:00:00,14.10,15.35,15.90,14.10,2020-12-31T00:00:00,14.10,2021-03-31T00:00:00,15.35,2021-06-30T00:00:00,15.35,2021-09-30T00:00:00,Yearly,ALBANIAGDP
2,Algeria,GDP,169.99,2019-12-31T00:00:00,140.00,155.00,165.00,140.00,2020-12-31T00:00:00,155.00,2021-03-31T00:00:00,155.00,2021-06-30T00:00:00,155.00,2021-09-30T00:00:00,Yearly,AlgeriaGDP
3,Andorra,GDP,3.15,2019-12-31T00:00:00,2.90,3.40,3.70,2.90,2020-12-31T00:00:00,3.40,2021-03-31T00:00:00,3.40,2021-06-30T00:00:00,3.40,2021-09-30T00:00:00,Yearly,ANDORRAGDP
4,Angola,GDP,94.64,2019-12-31T00:00:00,70.00,100.00,118.00,70.00,2020-12-31T00:00:00,100.00,2021-03-31T00:00:00,100.00,2021-06-30T00:00:00,100.00,2021-09-30T00:00:00,Yearly,AngolaGDP
5,Antigua And Barbuda,GDP,1.73,2019-12-31T00:00:00,1.58,1.64,1.70,1.58,2020-12-31T00:00:00,1.64,2021-03-31T00:00:00,1.64,2021-06-30T00:00:00,1.64,2021-09-30T00:00:00,Yearly,ANTIGUAANGDP
6,Argentina,GDP,449.70,2019-12-31T00:00:00,409.00,425.00,437.00,409.00,2020-12-31T00:00:00,425.00,2021-03-31T00:00:00,425.00,2021-06-30T00:00:00,425.00,2021-09-30T00:00:00,Yearly,WGDPARGE
7,Armenia,GDP,13.67,2019-12-31T00:00:00,9.80,11.00,14.00,9.80,2020-12-31T00:00:00,11.00,2021-03-31T00:00:00,11.00,2021-06-30T00:00:00,11.00,2021-09-30T00:00:00,Yearly,ARMENIAGDP
8,Aruba,GDP,3.06,2017-12-31T00:00:00,2.40,2.60,2.70,2.40,2020-12-31T00:00:00,2.60,2021-03-31T00:00:00,2.60,2021-06-30T00:00:00,2.60,2021-09-30T00:00:00,Yearly,ARUBAGDP
9,Australia,GDP,1392.70,2019-12-31T00:00:00,1320.00,1370.00,1480.00,1320.00,2020-12-31T00:00:00,1370.00,2021-03-31T00:00:00,1370.00,2021-06-30T00:00:00,1370.00,2021-09-30T00:00:00,Yearly,WGDPAUST

### 1.3 Markets

In [14]:
te.getHistorical('aapl:us')

         Date    Open     High       Low   Close   Symbol
0  02/11/2020  109.11  110.680  107.3200  108.77  AAPL:US
1  30/10/2020  111.06  111.990  107.7200  108.86  AAPL:US
2  29/10/2020  112.37  116.930  112.2000  115.32  AAPL:US
3  28/10/2020  115.05  115.430  111.1000  111.20  AAPL:US
4  27/10/2020  115.49  117.280  114.5399  116.60  AAPL:US
5  26/10/2020  114.01  116.550  112.8800  115.05  AAPL:US
6  23/10/2020  116.39  116.550  114.2800  115.04  AAPL:US
7  22/10/2020  117.45  118.040  114.5900  115.75  AAPL:US
8  21/10/2020  116.67  118.705  116.4500  116.87  AAPL:US
9  20/10/2020  116.20  118.980  115.6300  117.51  AAPL:US

In [36]:
te.fetchMarkets(symbol='indu:ind', initDate='2017-01-01', endDate='2017-06-15', output_type='df')[:2]

              symbol      open      high       low     close
2020-11-02  INDU:IND  26691.28  27043.48  26691.28  26925.05
2020-10-30  INDU:IND  26572.27  26639.18  26143.77  26501.60

In [37]:
te.fetchMarkets(symbol=['indu:ind', 'cl1:com'], initDate='2017-01-01', endDate='2017-06-15', output_type='df')[:2]

             symbol   open   high    low  close
2020-11-03  CL1:COM  36.70  38.27  36.57  38.16
2020-11-02  CL1:COM  35.24  37.15  33.64  36.81

In [31]:
te.getMarketsIntraday(symbols='indu:ind', output_type='df')[:2]

     Symbol                 Date     Open     High      Low    Close
0  INDU:IND  2020-11-03T12:23:00  27307.0  27320.0  27307.0  27318.0
1  INDU:IND  2020-11-03T12:22:00  27298.0  27305.0  27297.0  27305.0

In [18]:
te.getMarketsForecasts(symbol=['psi20:ind', 'indu:ind'], output_type='df')

,Symbol,Country,Date,Type,Last,Url,Importance,Forecast1,Forecast2,Forecast3,Forecast4
0,AAPL:US,United States,2020-11-02T20:59:00,stocks,108.77,NaN,500,106.638108,104.548001,102.498860,100.489882
1,DAX:IND,Germany,2020-11-03T12:19:00,index,11996.40,NaN,70,11512.434248,11242.482636,10979.603992,10722.619488
2,INDU:IND,United States,2020-11-03T12:18:00,index,27287.00,NaN,1,26526.682800,26007.188400,25495.811100,24997.962300

In [38]:
te.getEarnings(output_type='df')[:2]

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2020-11-01T00:00:00,PLOW:US,Douglas Dynamics,Earnings,0.42,0.34,FY2020Q3,Q3/20,2020/9,United States,USD,21,2020-11-03T09:26:00
1,2020-11-01T00:00:00,INGR:US,Ingredion,Earnings,1.77,1.45,None,None,2020/9,United States,USD,13,2020-11-03T09:26:00

In [39]:
te.getEarnings(symbols = 'msft:us', initDate='2016-01-01', endDate='2017-12-31', output_type='df')[:2]

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2016-01-26T00:00:00,AAPL:US,Apple,Earnings,3.28,None,FY2016Q1,Q1/16,2015/12,United States,USD,21.0,2017-08-03T21:30:00
1,2016-04-26T00:00:00,AAPL:US,Apple,Earnings,1.9,None,FY2016Q2,Q2/16,2016/3,United States,USD,21.0,2017-08-03T21:02:00

In [40]:
te.getEarnings(country = 'united states', output_type='df')[:2]

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2020-11-01T00:00:00,PLOW:US,Douglas Dynamics,Earnings,0.42,0.34,FY2020Q3,Q3/20,2020/9,United States,USD,21,2020-11-03T09:26:00
1,2020-11-01T00:00:00,INGR:US,Ingredion,Earnings,1.77,1.45,None,None,2020/9,United States,USD,13,2020-11-03T09:26:00

### 1.4 News

In [42]:
te.getNews(country =[ 'united states','China'],indicator=['Imports','Exports'])

,id,title,date,description,country,category,symbol,url
0,126072,US Imports Jump 3.2% to 6-Month High,2020-10-06T12:33:00,Imports to the United States rose by USD 7.4 b...,United States,Imports,TBIMTOT,/united-states/imports
1,126070,US Exports Rise 2.2% to 5-Month High,2020-10-06T12:31:00,Exports from the United States increased by US...,United States,Exports,TBEXTOT,/united-states/exports
2,123040,US Imports Surge Near 11%,2020-09-03T12:41:00,US imports jumped 10.9 percent month-over-mont...,United States,Imports,TBIMTOT,/united-states/imports
3,123038,US Exports at 4-Month High,2020-09-03T12:38:00,Exports from the US increased 8.2 percent to $...,United States,Exports,TBEXTOT,/united-states/exports
4,119415,US Imports Climb 4.7% in June,2020-08-05T12:41:57.083,Imports to the United States increased USD 9.5...,United States,Imports,TBIMTOT,/united-states/imports

In [24]:
te.getNews(country ='united states',indicator='Imports',start=10,limit=5)

,id,title,date,description,country,category,symbol,url
0,126072,US Imports Jump 3.2% to 6-Month High,2020-10-06T12:33:00,Imports to the United States rose by USD 7.4 b...,United States,Imports,TBIMTOT,/united-states/imports
1,123040,US Imports Surge Near 11%,2020-09-03T12:41:00,US imports jumped 10.9 percent month-over-mont...,United States,Imports,TBIMTOT,/united-states/imports
2,119415,US Imports Climb 4.7% in June,2020-08-05T12:41:57.083,Imports to the United States increased USD 9.5...,United States,Imports,TBIMTOT,/united-states/imports
3,116501,US Imports Drop to Decade Low in May,2020-07-02T12:35:00,Imports to the United States fell by USD 1.8 b...,United States,Imports,TBIMTOT,/united-states/imports
4,114093,US Imports Plunge 13.7%,2020-06-04T12:49:00,Imports to the US sank 13.7% to $200.7 billion...,United States,Imports,TBIMTOT,/united-states/imports

### 1.5 World Bank

In [25]:
te.getWBCategories(category = None)

[{'category': 'Agriculture'},
 {'category': 'Agriculture & Rural Development'},
 {'category': 'Aid Effectiveness'},
 {'category': 'Climate Change'},
 {'category': 'Demographics'},
 {'category': 'Development'},
 {'category': 'Economy & Growth'},
 {'category': 'Education'},
 {'category': 'Energy & Mining'},
 {'category': 'Environment'},
 {'category': 'External Debt'},
 {'category': 'Financial Sector'},
 {'category': 'Gender'},
 {'category': 'Health'},
 {'category': 'Infrastructure'},
 {'category': 'Poverty'},
 {'category': 'Private Sector'},
 {'category': 'Public Sector'},
 {'category': 'Science & Technology'},
 {'category': 'Social Protection & Labor'},
 {'category': 'Trade'},
 {'category': 'Urban Development'}]

In [43]:
te.getWBCategories(category = 'Demographics',page_number=2, output_type='df') [:2]

,category,series_code,series_name,sub_category,sub_category2,sub_category3,title,long_defenition,short_defenition,source,general_comments,aggregation_method,URL,organization,unit,verbose_unit,last_update
0,Demographics,CCX_HHCHI_POP_TOT,Share of households with children in total pop...,Social Protection & Labor,None,None,Share of households with children in total pop...,NaN,NaN,The Atlas of Social Protection: Indicators of ...,None,None,/country-list/share-of-households-with-childre...,The Atlas of Social Protection: Indicators of ...,%,%,2017-10-16T08:42:41.883
1,Demographics,CCX_HHELD_POP_TOT,Share of households with elderly in total popu...,Social Protection & Labor,None,None,Share of households with elderly in total popu...,NaN,NaN,The Atlas of Social Protection: Indicators of ...,None,None,/country-list/share-of-households-with-elderly...,The Atlas of Social Protection: Indicators of ...,%,%,2017-10-16T08:42:41.023

In [44]:
te.getWBIndicator(url = '/united-states/real-interest-rate-percent-wb-data.html', output_type='df')

,symbol,last,date,previous,previousDate,country,category,description,frequency,unit,title,URL,lastUpdate
0,USA.FR.INR.RINR,3.4782,2019-06-15T00:00:00,2.48582,2018-06-15T00:00:00,United States,Financial Sector,Real interest rate (%),yearly,%,Real interest rate,/united-states/real-interest-rate-percent-wb-d...,2020-11-01T17:28:17.5

In [46]:
te.getWBIndicator(series_code = 'usa.fr.inr.rinr', output_type='df')

,symbol,last,date,previous,previousDate,country,category,description,frequency,unit,title,URL,lastUpdate
0,USA.FR.INR.RINR,3.4782,2019-06-15T00:00:00,2.48582,2018-06-15T00:00:00,United States,Financial Sector,Real interest rate (%),yearly,%,Real interest rate,/united-states/real-interest-rate-percent-wb-d...,2020-11-01T17:28:17.5

In [48]:
te.getWBCountry(country = 'Portugal',page_number = 3, output_type='df')

,symbol,last,date,previous,previousDate,country,category,description,frequency,unit,title,URL,lastUpdate
0,PRT.AG.YLD.CREL.KG,4.728400e+03,2017-06-15T00:00:00,4.422400e+03,2016-06-15T00:00:00,Portugal,Agriculture & Rural Development,Cereal yield (kg per hectare),yearly,kg,Cereal yield (kg per hectare),/portugal/cereal-yield-kg-per-hectare-wb-data....,2020-10-18T22:08:40.15
1,PRT.BG.GSR.NFSV.GD.ZS,2.496831e+01,2019-06-15T00:00:00,2.406364e+01,2018-06-15T00:00:00,Portugal,Economy & Growth,Trade in services (% of GDP),yearly,%,Trade in services (% of GDP),/portugal/trade-in-services-percent-of-gdp-wb-...,2020-10-19T16:42:58.3
2,PRT.BM.GSR.CMCP.ZS,1.053295e+01,2019-06-15T00:00:00,1.066478e+01,2018-06-15T00:00:00,Portugal,Economy & Growth,"Communications, computer, etc. (% of service i...",yearly,%,"Communications, computer, etc. (% of service i...",/portugal/communications-computer-etc-percent-...,2020-10-19T16:56:48.487
3,PRT.BM.GSR.FCTY.CD,1.509075e+10,2019-06-15T00:00:00,1.664254e+10,2018-06-15T00:00:00,Portugal,Economy & Growth,"Primary income payments (BoP, current US$)",yearly,USD,"Income payments (BoP, current US$)",/portugal/income-payments-bop-us-dollar-wb-dat...,2020-10-19T17:13:49.457
4,PRT.BM.GSR.GNFS.CD,1.037317e+11,2019-06-15T00:00:00,1.039342e+11,2018-06-15T00:00:00,Portugal,Economy & Growth,"Imports of goods and services (BoP, current US$)",yearly,USD,"Imports of goods and services (BoP, current US$)",/portugal/imports-of-goods-and-services-bop-us...,2020-10-19T17:22:09.183
5,PRT.BM.GSR.INSF.ZS,5.733420e+00,2019-06-15T00:00:00,5.685570e+00,2018-06-15T00:00:00,Portugal,Economy & Growth,Insurance and financial services (% of service...,yearly,%,Insurance and financial services (% of service...,/portugal/insurance-and-financial-services-per...,2020-10-19T17:11:11.817
6,PRT.BM.GSR.MRCH.CD,8.383118e+10,2019-06-15T00:00:00,8.510651e+10,2018-06-15T00:00:00,Portugal,Economy & Growth,"Goods imports (BoP, current US$)",yearly,USD,"Goods imports (BoP, current US$)",/portugal/goods-imports-bop-us-dollar-wb-data....,2020-10-19T17:16:43.75
7,PRT.BM.GSR.NFSV.CD,1.990048e+10,2019-06-15T00:00:00,1.882888e+10,2018-06-15T00:00:00,Portugal,Economy & Growth,"Service imports (BoP, current US$)",yearly,USD,"Service imports (BoP, current US$)",/portugal/service-imports-bop-us-dollar-wb-dat...,2020-10-19T17:25:09.12
8,PRT.BM.GSR.ROYL.CD,8.485666e+08,2019-06-15T00:00:00,8.836979e+08,2018-06-15T00:00:00,Portugal,Economy & Growth,"Charges for the use of intellectual property, ...",yearly,USD,"Royalty and license fees, payments (BoP, curre...",/portugal/royalty-and-license-fees-payments-bo...,2020-10-19T17:27:58.907
9,PRT.BM.GSR.TOTL.CD,1.188224e+11,2019-06-15T00:00:00,1.205767e+11,2018-06-15T00:00:00,Portugal,Economy & Growth,"Imports of goods, services and primary income ...",yearly,USD,"Imports of goods, services and income (BoP, cu...",/portugal/imports-of-goods-services-and-income...,2020-10-19T17:19:36.483

### 1.5. Historical

In [52]:
te.getWBHistorical(series_code = 'usa.fr.inr.rinr', output_type='df')[:10]

            symbol                 date    value
0  usa.fr.inr.rinr  1961-06-15T00:00:00  3.10788
1  usa.fr.inr.rinr  1962-06-15T00:00:00  3.21535
2  usa.fr.inr.rinr  1963-06-15T00:00:00  3.37488
3  usa.fr.inr.rinr  1964-06-15T00:00:00  2.95167
4  usa.fr.inr.rinr  1965-06-15T00:00:00  2.56591
5  usa.fr.inr.rinr  1966-06-15T00:00:00  2.64942
6  usa.fr.inr.rinr  1967-06-15T00:00:00  2.40623
7  usa.fr.inr.rinr  1968-06-15T00:00:00  1.86391
8  usa.fr.inr.rinr  1969-06-15T00:00:00  2.85177
9  usa.fr.inr.rinr  1970-06-15T00:00:00  2.28032

### 1.6. Comtrade

In [54]:
te.getCmtCategories(category = None, output_type='df')[:10]

,id,name,parentId,pretty_name
0,01,Live animals,a1,Live animals
1,0101,"Horses, asses, mules and hinnies, live",01,"Horses, asses, mules and hinnies, live"
2,0102,"Bovine animals, live",01,"Bovine animals, live"
3,0103,"Swine, live",01,"Swine, live"
4,0104,"Sheep and goats, live",01,"Sheep and goats, live"
5,0105,"Chickens, ducks, geese, turkeys, and guineas, ...",01,"Chickens, ducks, geese, turkeys, and guineas, ..."
6,0106,Other live animals,01,"Animals, live, not specified elsewhere"
7,02,Meat & edible meat offal,a1,Meat and edible meat offal
8,0201,"Meat of bovine animals, fresh or chilled",02,"Meat of bovine animals, fresh or chilled"
9,0202,"Meat of bovine animals, frozen",02,"Meat of bovine animals, frozen"

In [56]:
te.getCmtCountry(country = 'China', output_type='df')[:10]

,symbol,country1,country2,type,category,url,title,lastupdate
0,CHN47300001,China,"LAIA, nes",Import,None,/china/imports/laia,"China imports from LAIA, nes",0001-01-01T00:00:00
1,CHN47300002,China,"LAIA, nes",Export,None,/china/exports/laia,"China exports to LAIA, nes",0001-01-01T00:00:00
2,CHN473XX011,China,"LAIA, nes",Import,Live animals,/china/imports/laia/live-animals,"China Imports from LAIA, nes of Live animals",0001-01-01T00:00:00
3,CHN473XX022,China,"LAIA, nes",Export,Meat and edible meat offal,/china/exports/laia/meat-edible-meat-offal,China exports of meat and edible meat offal to...,0001-01-01T00:00:00
4,CHN473XX031,China,"LAIA, nes",Import,"Fish, crustaceans, molluscs, aquatics inverteb...",/china/imports/laia/fish-crustaceans-molluscs-...,"China Imports from LAIA, nes of Fish, crustace...",0001-01-01T00:00:00
5,CHN473XX032,China,"LAIA, nes",Export,"Fish, crustaceans, molluscs, aquatics inverteb...",/china/exports/laia/fish-crustaceans-molluscs-...,"China exports of fish, crustaceans, molluscs, ...",0001-01-01T00:00:00
6,CHN473XX072,China,"LAIA, nes",Export,Edible vegetables and certain roots and tubers,/china/exports/laia/edible-vegetables-certain-...,China exports of edible vegetables and certain...,0001-01-01T00:00:00
7,CHN473XX122,China,"LAIA, nes",Export,"Oil seed, oleagic fruits, grain, seed, fruits",/china/exports/laia/oil-seed-oleagic-fruits-gr...,"China exports of oil seed, oleagic fruits, gra...",0001-01-01T00:00:00
8,CHN473XX182,China,"LAIA, nes",Export,Cocoa and cocoa preparations,/china/exports/laia/cocoa-cocoa-preparations,China exports of cocoa and cocoa preparations ...,0001-01-01T00:00:00
9,CHN473XX202,China,"LAIA, nes",Export,"Vegetable, fruit, nut food preparations",/china/exports/laia/vegetable-fruit-nut-food-p...,"China exports of vegetable, fruit, nut food pr...",0001-01-01T00:00:00

In [58]:
te.getCmtCountry(country =['China','Portugal'],page_number=3, output_type='df')[:10]

,symbol,country1,country2,type,category,url,title,lastupdate
0,CHNPRT05022,China,Portugal,Export,"Hogs' hair, badger hair, waste hair",/china/exports/portugal/hogs-hair-badger-hair-...,"China exports of hogs' hair, badger hair, wast...",0001-01-01T00:00:00
1,CHNPRT05041,China,Portugal,Import,"Animal (not fish) guts, bladders, stomachs and...",/china/imports/portugal/animal-not-fish-guts-b...,China Imports from Portugal of Animal (not fis...,0001-01-01T00:00:00
2,CHNPRT05042,China,Portugal,Export,"Animal (not fish) guts, bladders, stomachs and...",/china/exports/portugal/animal-not-fish-guts-b...,"China exports of animal (not fish) guts, bladd...",0001-01-01T00:00:00
3,CHNPRT05052,China,Portugal,Export,Bird skins and other feathered parts and down,/china/exports/portugal/bird-skins-feathered-p...,China exports of bird skins and other feathere...,0001-01-01T00:00:00
4,CHNPRT05081,China,Portugal,Import,"Coral, shell of molluscs unworked powder/waste",/china/imports/portugal/coral-shell-molluscs-u...,"China Imports from Portugal of Coral, shell of...",0001-01-01T00:00:00
5,CHNPRT05082,China,Portugal,Export,"Coral, shell of molluscs unworked powder/waste",/china/exports/portugal/coral-shell-molluscs-u...,"China exports of coral, shell of molluscs unwo...",0001-01-01T00:00:00
6,CHNPRT05102,China,Portugal,Export,"Ambergris, castoreum, glands for pharmacy",/china/exports/portugal/ambergris-castoreum-gl...,"China exports of ambergris, castoreum, glands ...",0001-01-01T00:00:00
7,CHNPRT05111,China,Portugal,Import,"Animal products not specified elsewhere, dead ...",/china/imports/portugal/animal-products-dead-a...,China Imports from Portugal of Animal products...,0001-01-01T00:00:00
8,CHNPRT05112,China,Portugal,Export,"Animal products not specified elsewhere, dead ...",/china/exports/portugal/animal-products-dead-a...,China exports of animal products not specified...,0001-01-01T00:00:00
9,CHNPRT06021,China,Portugal,Import,"Live plants not specified elsewhere, cuttings,...",/china/imports/portugal/live-plants-cuttings-m...,China Imports from Portugal of Live plants not...,0001-01-01T00:00:00

In [59]:
te.getHistorical('PRTESP24031:comtrade', output_type='df')[:10]

        symbol                 date     value
0  PRTESP24031  1997-12-31T00:00:00     707.0
1  PRTESP24031  1998-12-31T00:00:00    7020.0
2  PRTESP24031  2000-12-31T00:00:00   54310.0
3  PRTESP24031  2002-12-31T00:00:00   89710.0
4  PRTESP24031  2003-12-31T00:00:00    5290.0
5  PRTESP24031  2004-12-31T00:00:00    8792.0
6  PRTESP24031  2005-12-31T00:00:00    5730.0
7  PRTESP24031  2006-12-31T00:00:00  294690.0
8  PRTESP24031  2007-12-31T00:00:00  340640.0
9  PRTESP24031  2008-12-31T00:00:00  156900.0

## 2. Financial Modeling Prep API

- Ideal for Testing your ideas
- **Limited**
- Personal use
- Upgrade anytime
- 250 requests / day
- Limited to 5 years and 5 quarters

In [157]:
YOUR_API_KEY = '<YOUR_API_KEY>' # Free and easy to get

In [67]:
import requests 

url = "https://financialmodelingprep.com"
query_format = "{}/{}?apikey={}"

In [68]:
# Company Profile
query = query_format.format( url, "/api/v3/profile/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'price': 108.77,
  'beta': 1.33758,
  'volAvg': 168829570,
  'mktCap': 1849285670000,
  'lastDiv': 0.7825,
  'range': '53.1525-137.98',
  'changes': -0.09,
  'companyName': 'Apple Inc',
  'currency': 'USD',
  'cik': '0000320193',
  'isin': 'US0378331005',
  'cusip': '037833100',
  'exchange': 'Nasdaq Global Select',
  'exchangeShortName': 'NASDAQ',
  'industry': 'Consumer Electronics',
  'website': 'https://www.apple.com/',
  'description': "Apple, Inc. engages in the design, manufacture, and sale of smartphones, personal computers, tablets, wearables and accessories, and other variety of related services. The company is headquartered in Cupertino, California and currently employs 137,000 full-time employees. The company is considered one of the Big Four technology companies, alongside Amazon, Google, and Microsoft. The firm's hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, the AirPods wireless earbuds and the HomePod smart speaker. Apple's software includes the macOS, iOS, iPadOS, watchOS, and tvOS operating systems, the iTunes media player, the Safari web browser, the Shazam acoustic fingerprint utility, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Music, Apple TV+, iMessage, and iCloud. Other services include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, and Apple Card.",
  'ceo': 'Mr. Timothy Cook',
  'sector': 'Technology',
  'country': 'US',
  'fullTimeEmployees': '137000',
  'phone': '14089961010',
  'address': '1 Apple Park Way',
  'city': 'Cupertino',
  'state': 'CALIFORNIA',
  'zip': '95014',
  'dcfDiff': 89.92,
  'dcf': 127.377,
  'image': 'https://financialmodelingprep.com/image-stock/AAPL.png',
  'ipoDate': '1980-12-12',
  'defaultImage': False}]

In [69]:
# Company Quote
query = query_format.format( url, "/api/v3/quote/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'name': 'Apple Inc.',
  'price': 108.77,
  'changesPercentage': -0.08,
  'change': -0.09,
  'dayLow': 107.32,
  'dayHigh': 110.67,
  'yearHigh': 137.98,
  'yearLow': 53.1525,
  'marketCap': 1849285672960.0,
  'priceAvg50': 114.56778,
  'priceAvg200': 99.327156,
  'volume': 122866899,
  'avgVolume': 168829570,
  'exchange': 'NASDAQ',
  'open': 109.11,
  'previousClose': 108.86,
  'eps': 3.28,
  'pe': 33.161583,
  'earningsAnnouncement': '2020-10-29T16:30:00.000+0000',
  'sharesOutstanding': 17001798961,
  'timestamp': 1604407677}]

In [70]:
# Key Executives
query = query_format.format( url, "/api/v3/key-executives/AAPL", YOUR_API_KEY ) # LIMITED FOR PREMIUM MEMBERS
r = requests.get(query)
r.json()

{'Error Message': 'Special Endpoint : this endpoint is only for premium members please visit our subsription page to upgrade your plan at https://financialmodelingprep.com/developer/docs/pricing'}

In [72]:
search_query_format = "{}/{}&apikey={}"

query = search_query_format.format( url, "/api/v3/search?query=AA&limit=10&exchange=NASDAQ", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAWW',
  'name': 'Atlas Air Worldwide Holdings Inc',
  'currency': 'USD',
  'stockExchange': 'NasdaqGS',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'AAL',
  'name': 'American Airlines Group Inc',
  'currency': 'USD',
  'stockExchange': 'NasdaqGS',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'CPAAW',
  'name': 'Conyers Park II Acquisition Corp.',
  'currency': None,
  'stockExchange': 'NasdaqCM',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'PRAA',
  'name': 'PRA Group Inc',
  'currency': 'USD',
  'stockExchange': 'NasdaqGS',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'PAAS',
  'name': 'Pan American Silver Corp',
  'currency': 'USD',
  'stockExchange': 'NasdaqGS',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'RYAAY',
  'name': 'Ryanair Holdings plc',
  'currency': 'USD',
  'stockExchange': 'NasdaqGS',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'AAXN',
  'name': 'Axon Enterprise Inc',
  'currency': 'USD',
  'stockExchange': 'NasdaqGS',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'CAAS',
  'name': 'China Automotive Systems Inc',
  'currency': 'USD',
  'stockExchange': 'NasdaqCM',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'ZNWAA',
  'name': 'Zion Oil & Gas, Inc.',
  'currency': 'USD',
  'stockExchange': 'NasdaqCM',
  'exchangeShortName': 'NASDAQ'},
 {'symbol': 'CAN',
  'name': 'Canaan Inc',
  'currency': 'USD',
  'stockExchange': 'NasdaqGM',
  'exchangeShortName': 'NASDAQ'}]

In [76]:
# Company Financial Statements

### Annual income statemets
query = search_query_format.format( url, "/api/v3/income-statement/AAPL?limit=2", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'date': '2020-09-26',
  'symbol': 'AAPL',
  'fillingDate': '2020-10-30',
  'acceptedDate': '2020-10-29 18:06:25',
  'period': 'FY',
  'revenue': 274515000000,
  'costOfRevenue': 169559000000,
  'grossProfit': 104956000000,
  'grossProfitRatio': 0.382332477278109,
  'researchAndDevelopmentExpenses': 18752000000,
  'generalAndAdministrativeExpenses': 19916000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 803000000,
  'operatingExpenses': 38668000000,
  'costAndExpenses': 208227000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 11056000000,
  'ebitda': 77344000000,
  'ebitdaratio': 0.281747809773601,
  'operatingIncome': 66288000000,
  'operatingIncomeRatio': 0.241473143544069,
  'totalOtherIncomeExpensesNet': 803000000,
  'incomeBeforeTax': 67091000000,
  'incomeBeforeTaxRatio': 0.244398302460703,
  'incomeTaxExpense': 9680000000,
  'netIncome': 57411000000,
  'netIncomeRatio': 0.209136112780722,
  'eps': 3.31,
  'epsdiluted': 3.28,
  'weightedAverageShsOut': 17352119000000,
  'weightedAverageShsOutDil': 17528214000000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/0000320193-20-000096-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/aapl-20200926.htm'},
 {'date': '2019-09-28',
  'symbol': 'AAPL',
  'fillingDate': '2019-10-31 00:00:00',
  'acceptedDate': '2019-10-30 18:12:36',
  'period': 'FY',
  'revenue': 260174000000,
  'costOfRevenue': 161782000000,
  'grossProfit': 98392000000,
  'grossProfitRatio': 0.378178,
  'researchAndDevelopmentExpenses': 16217000000,
  'generalAndAdministrativeExpenses': 18245000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 1807000000,
  'operatingExpenses': 34462000000,
  'costAndExpenses': 196244000000,
  'interestExpense': 3576000000,
  'depreciationAndAmortization': 12547000000,
  'ebitda': 81860000000,
  'ebitdaratio': 0.314636,
  'operatingIncome': 63930000000,
  'operatingIncomeRatio': 0.24572,
  'totalOtherIncomeExpensesNet': 422000000,
  'incomeBeforeTax': 65737000000,
  'incomeBeforeTaxRatio': 0.252666,
  'incomeTaxExpense': 10481000000,
  'netIncome': 55256000000,
  'netIncomeRatio': 0.212381,
  'eps': 2.97145,
  'epsdiluted': 2.97145,
  'weightedAverageShsOut': 18595652000,
  'weightedAverageShsOutDil': 18595652000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019319000119/0000320193-19-000119-index.html',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019319000119/a10-k20199282019.htm'}]

In [77]:
### Quarterly income statements
query = search_query_format.format( url, "/api/v3/income-statement/AAPL?period=quarter&limit=2", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'date': '2020-09-26',
  'symbol': 'AAPL',
  'fillingDate': '2020-10-30',
  'acceptedDate': '2020-10-29 18:06:25',
  'period': 'FY',
  'revenue': 64698000000,
  'costOfRevenue': 40009000000,
  'grossProfit': 24689000000,
  'grossProfitRatio': 0.3816037590033695,
  'researchAndDevelopmentExpenses': 4978000000,
  'generalAndAdministrativeExpenses': 4936000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 126000000,
  'operatingExpenses': 9914000000,
  'costAndExpenses': 49923000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 2702000000,
  'ebitda': 17477000000,
  'ebitdaratio': 0.27013199789792575,
  'operatingIncome': 14775000000,
  'operatingIncomeRatio': 0.2283687285542057,
  'totalOtherIncomeExpensesNet': 126000000,
  'incomeBeforeTax': 14901000000,
  'incomeBeforeTaxRatio': 0.23031623852360197,
  'incomeTaxExpense': 2228000000,
  'netIncome': 12673000000,
  'netIncomeRatio': 0.19587931620761073,
  'eps': 3.31,
  'epsdiluted': 3.28,
  'weightedAverageShsOut': 17352119000,
  'weightedAverageShsOutDil': 17528214000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/0000320193-20-000096-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/aapl-20200926.htm'},
 {'date': '2020-06-27',
  'symbol': 'AAPL',
  'fillingDate': '2020-07-31',
  'acceptedDate': '2020-07-30 19:29:09',
  'period': 'Q3',
  'revenue': 59685000000,
  'costOfRevenue': 37005000000,
  'grossProfit': 22680000000,
  'grossProfitRatio': 0.3799949736114602,
  'researchAndDevelopmentExpenses': 4758000000,
  'generalAndAdministrativeExpenses': 4831000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 46000000,
  'operatingExpenses': 9589000000,
  'costAndExpenses': 46594000000,
  'interestExpense': 697000000,
  'depreciationAndAmortization': 2752000000,
  'ebitda': 16586000000,
  'ebitdaratio': 0.277892,
  'operatingIncome': 13091000000,
  'operatingIncomeRatio': 0.219335,
  'totalOtherIncomeExpensesNet': -158000000,
  'incomeBeforeTax': 13137000000,
  'incomeBeforeTaxRatio': 0.220106,
  'incomeTaxExpense': 1884000000,
  'netIncome': 11253000000,
  'netIncomeRatio': 0.18854,
  'eps': 0.64601,
  'epsdiluted': 0.64601,
  'weightedAverageShsOut': 17419152000,
  'weightedAverageShsOutDil': 17419152000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000062/0000320193-20-000062-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000062/aapl-20200627.htm'}]

In [80]:
### Downloable file
query = search_query_format.format( url, "/api/v3/income-statement/AAPL?datatype=csv", YOUR_API_KEY )
r = requests.get(query)

In [82]:
# Balance Sheet Statement

### Annual balance sheet statement
query = search_query_format.format( url, "/api/v3/balance-sheet-statement/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'date': '2020-09-26',
  'symbol': 'AAPL',
  'fillingDate': '2020-10-30',
  'acceptedDate': '2020-10-29 18:06:25',
  'period': 'FY',
  'cashAndCashEquivalents': 38016000000,
  'shortTermInvestments': 52927000000,
  'cashAndShortTermInvestments': 90943000000,
  'netReceivables': 16120000000,
  'inventory': 4061000000,
  'otherCurrentAssets': 32589000000,
  'totalCurrentAssets': 143713000000,
  'propertyPlantEquipmentNet': 36766000000,
  'goodwill': 0.0,
  'intangibleAssets': 0.0,
  'goodwillAndIntangibleAssets': 0.0,
  'longTermInvestments': 100887000000,
  'taxAssets': 0.0,
  'otherNonCurrentAssets': 42522000000,
  'totalNonCurrentAssets': 180175000000,
  'otherAssets': 90482000000,
  'totalAssets': 323888000000,
  'accountPayables': 42296000000,
  'shortTermDebt': 8773000000,
  'taxPayables': 0.0,
  'deferredRevenue': 6643000000,
  'otherCurrentLiabilities': 47680000000,
  'totalCurrentLiabilities': 105392000000,
  'longTermDebt': 98667000000,
  'deferredRevenueNonCurrent': 0.0,
  'deferredTaxLiabilitiesNonCurrent': 0.0,
  'otherNonCurrentLiabilities': 54490000000,
  'totalNonCurrentLiabilities': 153157000000,
  'otherLiabilities': 0.0,
  'totalLiabilities': 258549000000,
  'commonStock': 16976763000,
  'retainedEarnings': 14966000000,
  'accumulatedOtherComprehensiveIncomeLoss': -406000000,
  'othertotalStockholdersEquity': 33802237000,
  'totalStockholdersEquity': 65339000000,
  'totalLiabilitiesAndStockholdersEquity': 323888000000,
  'totalInvestments': 153814000000,
  'totalDebt': 107440000000,
  'netDebt': 69424000000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/0000320193-20-000096-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/aapl-20200926.htm'}]

In [84]:
# Cash Flow Statement
query = search_query_format.format( url, "/api/v3/cash-flow-statement/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'date': '2020-09-26',
  'symbol': 'AAPL',
  'fillingDate': '2020-10-30',
  'acceptedDate': '2020-10-29 18:06:25',
  'period': 'FY',
  'netIncome': 57411000000,
  'depreciationAndAmortization': 11056000000,
  'deferredIncomeTax': -215000000,
  'stockBasedCompensation': 6829000000,
  'changeInWorkingCapital': -18780000000,
  'accountsReceivables': 6917000000,
  'inventory': -127000000,
  'accountsPayables': -4062000000,
  'otherWorkingCapital': 38321000000,
  'otherNonCashItems': 0.0,
  'netCashProvidedByOperatingActivities': 80674000000,
  'investmentsInPropertyPlantAndEquipment': -7309000000,
  'acquisitionsNet': -1524000000,
  'purchasesOfInvestments': -114938000000,
  'salesMaturitiesOfInvestments': 0.0,
  'otherInvestingActivites': 0.0,
  'netCashUsedForInvestingActivites': -4289000000,
  'debtRepayment': -12629000000,
  'commonStockIssued': 880000000,
  'commonStockRepurchased': -72358000000,
  'dividendsPaid': -14081000000,
  'otherFinancingActivites': 0.0,
  'netCashUsedProvidedByFinancingActivities': -86820000000,
  'effectOfForexChangesOnCash': 0.0,
  'netChangeInCash': -10435000000,
  'cashAtEndOfPeriod': 39789000000,
  'cashAtBeginningOfPeriod': 50224000000,
  'operatingCashFlow': 80674000000,
  'capitalExpenditure': 7309000000,
  'freeCashFlow': 73365000000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/0000320193-20-000096-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/aapl-20200926.htm'}]

In [90]:
# Cash Flow Statement
query = query_format.format( url, "/api/v3/financial-statement-symbol-lists", YOUR_API_KEY )
r = requests.get(query)
r.json()[:5]

['BFG.AX', 'SRDX', 'JMG.L', '0O1S.L', 'BSP.AX']

In [92]:
# Income Statements Growth
query = search_query_format.format( url, "/api/v3/income-statement-growth/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'date': '2020-09-26',
  'symbol': 'AAPL',
  'period': 'FY',
  'growthRevenue': 0.055120803769784836,
  'growthCostOfRevenue': 0.04807086078797394,
  'growthGrossProfit': 0.06671274087324172,
  'growthGrossProfitRatio': 0.01098550756022024,
  'growthResearchAndDevelopmentExpenses': 0.15631744465684158,
  'growthGeneralAndAdministrativeExpenses': 0.09158673609208003,
  'growthSellingAndMarketingExpenses': 0.0,
  'growthOtherExpenses': -0.5556170448256779,
  'growthOperatingExpenses': 0.12204747257849226,
  'growthCostAndExpenses': 0.0610617394671939,
  'growthInterestExpense': -1.0,
  'growthDepreciationAndAmortization': -0.11883318721606759,
  'growthEBITDA': -0.05516735890544833,
  'growthEBITDARatio': -0.10452774071116798,
  'growthOperatingIncome': 0.03688409197559831,
  'growthOperatingIncomeRatio': -0.01728331619701685,
  'growthTotalOtherIncomeExpensesNet': 0.9028436018957346,
  'growthIncomeBeforeTax': 0.020597228349331427,
  'growthIncomeBeforeTaxRatio': -0.0327218444084167,
  'growthIncomeTaxExpense': -0.07642400534300162,
  'growthNetIncome': 0.039000289561314606,
  'growthNetIncomeRatio': -0.015278613526059236,
  'growthEPS': 0.11393427451244346,
  'growthEPSDiluted': 0.10383819347456626,
  'growthWeightedAverageShsOut': 932.1277548106407,
  'growthWeightedAverageShsOutDil': 941.597441595487}]

In [93]:
# Annual Balance Sheet Growth
query = search_query_format.format( url, "/api/v3/balance-sheet-statement-growth/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'date': '2020-09-26',
  'symbol': 'AAPL',
  'period': 'FY',
  'growthCashAndCashEquivalents': -0.2216853656539186,
  'growthShortTermInvestments': 0.023475721772088256,
  'growthCashAndShortTermInvestments': -0.09560746641208469,
  'growthNetReceivables': -0.6480656711204261,
  'growthInventory': -0.010959571358986848,
  'growthOtherCurrentAssets': 1.6383581606217616,
  'growthTotalCurrentAssets': -0.11734502730025366,
  'growthPropertyPlantEquipmentNet': -0.016373267697576115,
  'growthGoodwill': 0,
  'growthIntangibleAssets': 0,
  'growthGoodwillAndIntangibleAssets': 0,
  'growthLongTermInvestments': -0.04228173265869889,
  'growthTaxAssets': 0,
  'growthOtherNonCurrentAssets': 0.28940505791739946,
  'growthTotalNonCurrentAssets': 0.02548706010916521,
  'growthOtherAssets': 0.9960732406794617,
  'growthTotalAssets': -0.04321213768330005,
  'growthAccountPayables': -0.08521498399515529,
  'growthShortTermDebt': 0.467056856187291,
  'growthTaxPayables': 0,
  'growthDeferredRevenue': 0.2030061571894241,
  'growthOtherCurrentLiabilities': 0.10263170066139402,
  'growthTotalCurrentLiabilities': -0.0030836754384305416,
  'growthLongTermDebt': 0.07472197109152896,
  'growthDeferredRevenueNonCurrent': 0,
  'growthDeferrredTaxLiabilitiesNonCurrent': 0,
  'growthOtherNonCurrentLiabilities': 0.0789458051996911,
  'growthTotalNonCurrentLiabilities': 0.07622092614714356,
  'growthOtherLiabilities': -1,
  'growthTotalLiabilities': 0.04241859790023707,
  'growthCommonStock': -0.6241917253287289,
  'growthRetainedEarnings': -0.6739291472395311,
  'growthAccumulatedOtherComprehensiveIncomeLoss': -0.3047945205479452,
  'growthOthertotalStockholdersEquity': -27.182987606506583,
  'growthTotalStockholdersEquity': -0.27792635487578465,
  'growthTotalLiabilitiesAndStockholdersEquity': -0.04321213768330005,
  'growthTotalInvestments': -0.020629847058973347,
  'growthTotalDebt': -0.005617925532407193,
  'growthNetDebt': 0.17264327821225275}]

In [94]:
# Annual cash flow Sheet Growth
query = search_query_format.format( url, "/api/v3/cash-flow-statement-growth/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'date': '2020-09-26',
  'symbol': 'AAPL',
  'period': 'FY',
  'growthNetIncome': 0.039000289561314606,
  'growthDepreciationAndAmortization': -0.11883318721606759,
  'growthDeferredIncomeTax': -0.36764705882352944,
  'growthStockBasedCompensation': 0.12541199736321687,
  'growthChangeInWorkingCapital': -1.4504569331510397,
  'growthAccountsReceivables': 27.23265306122449,
  'growthInventory': -0.5605536332179931,
  'growthAccountsPayables': 1.1123244929797191,
  'growthOtherWorkingCapital': -0.3288909125934747,
  'growthOtherNonCashItems': -1,
  'growthNetCashProvidedByOperatingActivites': 0.16260033721952413,
  'growthInvestmentsInPropertyPlantAndEquipment': -0.30357313006193426,
  'growthAcquisitionsNet': 1.4423076923076923,
  'growthPurchasesOfInvestments': 0.06891228331225355,
  'growthSalesMaturitiesOfInvestments': -1,
  'growthOtherInvestingActivites': -1,
  'growthNetCashUsedForInvestingActivites': -1.0934504096217534,
  'growthDebtRepayment': 0.43429869392390685,
  'growthCommonStockIssued': 0.1267605633802817,
  'growthCommonStockRepurchased': 0.0944098251557868,
  'growthDividendsPaid': -0.0026914087399957506,
  'growthOtherFinancingActivites': -1,
  'growthNetCashUsedProvidedByFinancingActivities': -0.045682377769961306,
  'growthEffectOfForexChangesOnCash': 0,
  'growthNetChangeInCash': -1.429229566862737,
  'growthCashAtEndOfPeriod': -0.20776919401083146,
  'growthCashAtBeginningOfPeriod': 0.9381777486203836,
  'growthOperatingCashFlow': 0.16260033721952413,
  'growthCapitalExpenditure': -1.6964268699380658,
  'growthFreeCashFlow': 0.24567033414832926}]

In [96]:
# Company Financial Ratios

# FORMULAS EXPLAINED HERE: https://financialmodelingprep.com/developer/docs/formula/
query = search_query_format.format( url, "/api/v3/ratios/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'date': '2020-09-26',
  'currentRatio': 1.3636044481554577,
  'quickRatio': 1.0158550933657204,
  'cashRatio': 0.36071049035979963,
  'daysOfSalesOutstanding': 21.433437152796753,
  'daysOfInventoryOutstanding': 8.741883356235881,
  'operatingCycle': 30.175320509032634,
  'daysOfPayablesOutstanding': 91.04818971567418,
  'cashConversionCycle': -60.87286920664155,
  'grossProfitMargin': 0.38233247727810865,
  'operatingProfitMargin': 0.24147314354406862,
  'pretaxProfitMargin': 0.24439830246070343,
  'netProfitMargin': 0.20913611278072236,
  'effectiveTaxRate': 0.14428164731484103,
  'returnOnAssets': 0.1772557180259843,
  'returnOnEquity': 0.8786635853012749,
  'returnOnCapitalEmployed': 0.30705825278265964,
  'netIncomePerEBT': 0.855718352685159,
  'ebtPerEbit': 1.0,
  'ebitPerRevenue': 0.24439830246070343,
  'debtRatio': 0.7982666847799239,
  'debtEquityRatio': 3.957039440456695,
  'longTermDebtToCapitalization': 0.6016060388034584,
  'totalDebtToCapitalization': 0.6218348294642289,
  'interestCoverage': None,
  'cashFlowToDebtRatio': 0.7508749069247952,
  'companyEquityMultiplier': 4.957039440456695,
  'receivablesTurnover': 17.029466501240694,
  'payablesTurnover': 4.008866086627577,
  'inventoryTurnover': 41.75301649839941,
  'fixedAssetTurnover': 7.466545177609748,
  'assetTurnover': 0.8475615027416885,
  'operatingCashFlowPerShare': 0.0046492304484541625,
  'freeCashFlowPerShare': 0.0042280138811865,
  'cashPerShare': 0.0052410313691371065,
  'payoutRatio': 0.24526658654264863,
  'operatingCashFlowSalesRatio': 0.2938782944465694,
  'freeCashFlowOperatingCashFlowRatio': 0.909400798274537,
  'cashFlowCoverageRatios': 0.7508749069247952,
  'shortTermCoverageRatios': 9.195714122877009,
  'capitalExpenditureCoverageRatio': 11.037624846080176,
  'dividendPaidAndCapexCoverageRatio': 3.771575502571295,
  'dividendPayoutRatio': 0.2452665865426486,
  'priceBookValueRatio': 30553.90108520726,
  'priceToBookRatio': 30553.90108520726,
  'priceToSalesRatio': 7272.321523437178,
  'priceEarningsRatio': 34773.15049391853,
  'priceToFreeCashFlowsRatio': 27211.358863304806,
  'priceToOperatingCashFlowsRatio': 24746.03147242429,
  'priceCashFlowRatio': 24746.03147242429,
  'priceEarningsToGrowthRatio': 10919861.107850427,
  'priceSalesRatio': 7272.321523437178,
  'dividendYield': 7.053332328502797e-06,
  'enterpriseValueMultiple': 25812.35476580416,
  'priceFairValue': 30553.90108520726}]

In [97]:
# Company Enterprise Value
query = search_query_format.format( url, "/api/v3/enterprise-values/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'date': '2020-09-26',
  'stockPrice': 115.050003,
  'numberOfShares': 17352119000000,
  'marketCapitalization': 1996361343006357,
  'minusCashAndCashEquivalents': 38016000000,
  'addTotalDebt': 107440000000,
  'enterpriseValue': 1996430767006357}]

In [98]:
# Company Key Metrics
query = search_query_format.format( url, "/api/v3/key-metrics-ttm/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'revenuePerShareTTM': 15.820258033039078,
  'netIncomePerShareTTM': 3.3085872682177895,
  'operatingCashFlowPerShareTTM': 1.758632475952937,
  'freeCashFlowPerShareTTM': 1.6372063838428033,
  'cashPerShareTTM': 2.190856344403816,
  'bookValuePerShareTTM': 3.765476712094932,
  'tangibleBookValuePerShareTTM': 18.66561657397578,
  'shareholdersEquityPerShareTTM': 3.765476712094932,
  'interestDebtPerShareTTM': 6.320784222376529,
  'marketCapTTM': 1887389983630,
  'enterpriseValueTTM': 1956813983630,
  'peRatioTTM': 32.87505850150668,
  'priceToSalesRatioTTM': 6.875361942443946,
  'pocfratioTTM': 61.849193329073266,
  'pfcfRatioTTM': 66.43634002006407,
  'pbRatioTTM': 28.886116769923017,
  'ptbRatioTTM': 28.886116769923017,
  'evToSalesTTM': 7.128258869752108,
  'enterpriseValueOverEBITDATTM': 24.380936750934463,
  'evToOperatingCashFlowTTM': 64.12419660604273,
  'evToFreeCashFlowTTM': 68.88007264000845,
  'earningsYieldTTM': 0.030418196820978117,
  'freeCashFlowYieldTTM': 0.015052003161191535,
  'debtToEquityTTM': 3.957039440456695,
  'debtToAssetsTTM': 0.7982666847799239,
  'netDebtToEBITDATTM': 0.8649887864440569,
  'currentRatioTTM': 1.3636044481554577,
  'interestCoverageTTM': 29.964716391246093,
  'incomeQualityTTM': 0.5315357684067513,
  'dividendYieldTTM': 0.007309000643559806,
  'dividendYieldPercentageTTM': 0.7309000643559806,
  'payoutRatioTTM': 0.24028382374457857,
  'salesGeneralAndAdministrativeToRevenueTTM': None,
  'researchAndDevelopementToRevenueTTM': 0.06830956414039306,
  'intangiblesToTotalAssetsTTM': 0.0,
  'capexToOperatingCashFlowTTM': -14.483151400094922,
  'capexToRevenueTTM': -130.28713811105837,
  'capexToDepreciationTTM': -1.336497389653536,
  'stockBasedCompensationToRevenueTTM': 0.006229167805037976,
  'grahamNumberTTM': 16.74258602902124,
  'roicTTM': 0.30705825278265964,
  'returnOnTangibleAssetsTTM': 0.1772557180259843,
  'grahamNetNetTTM': -8.845346208148987,
  'workingCapitalTTM': 38321000000,
  'tangibleAssetValueTTM': None,
  'netCurrentAssetValueTTM': -6.617981354323354,
  'investedCapitalTTM': None,
  'averageReceivablesTTM': 24097500000,
  'averagePayablesTTM': 38810500000,
  'averageInventoryTTM': 4019500000,
  'daysSalesOutstandingTTM': 5.284957106169062,
  'daysPayablesOutstandingTTM': 22.450238560029252,
  'daysOfInventoryOnHandTTM': 2.1555328823595326,
  'receivablesTurnoverTTM': 17.029466501240694,
  'payablesTurnoverTTM': 4.008866086627577,
  'inventoryTurnoverTTM': 41.75301649839941,
  'roeTTM': 0.8786635853012749,
  'capexPerShareTTM': -0.12142609211013364}]

In [99]:
# Company Financial Growth 
query = search_query_format.format( url, "/api/v3/financial-growth/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'date': '2020-09-26',
  'revenueGrowth': 0.055120803769784836,
  'grossProfitGrowth': 0.06671274087324172,
  'ebitgrowth': 0.03688409197559831,
  'operatingIncomeGrowth': 0.03688409197559831,
  'netIncomeGrowth': 0.039000289561314606,
  'epsgrowth': 0.11393427451244346,
  'epsdilutedGrowth': 0.10383819347456626,
  'weightedAverageSharesGrowth': 932.1277548106407,
  'weightedAverageSharesDilutedGrowth': 941.597441595487,
  'dividendsperShareGrowth': -0.9989312196683482,
  'operatingCashFlowGrowth': 0.16260033721952413,
  'freeCashFlowGrowth': 0.24567033414832926,
  'tenYRevenueGrowthPerShare': -0.9937199214872909,
  'fiveYRevenueGrowthPerShare': -0.998431459745704,
  'threeYRevenueGrowthPerShare': -0.998550247824493,
  'tenYOperatingCFGrowthPerShare': -0.9935263310152528,
  'fiveYOperatingCFGrowthPerShare': -0.9986743133519653,
  'threeYOperatingCFGrowthPerShare': -0.9984793257234844,
  'tenYNetIncomeGrowthPerShare': -0.9938866808286094,
  'fiveYNetIncomeGrowthPerShare': -0.9985641177407719,
  'threeYNetIncomeGrowthPerShare': -0.9985625380002233,
  'tenYShareholdersEquityGrowthPerShare': -0.9979599564137691,
  'fiveYShareholdersEquityGrowthPerShare': -0.9992689483838613,
  'threeYShareholdersEquityGrowthPerShare': -0.9994099047669819,
  'tenYDividendperShareGrowthPerShare': 0.0,
  'fiveYDividendperShareGrowthPerShare': -0.9983734992324528,
  'threeYDividendperShareGrowthPerShare': -0.9986649936445103,
  'receivablesGrowth': -0.6480656711204261,
  'inventoryGrowth': -0.010959571358986848,
  'assetGrowth': -0.04321213768330005,
  'bookValueperShareGrowth': 0.0,
  'debtGrowth': -0.005617925532407193,
  'rdexpenseGrowth': 0.15631744465684158,
  'sgaexpensesGrowth': 0.09158673609208003}]

### 2.1. Useful data:

In [100]:
# Company Rating
query = search_query_format.format( url, "/api/v3/rating/AAPL?limit=1", YOUR_API_KEY ) # DAILY
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'date': '2020-10-30',
  'rating': 'S-',
  'ratingScore': 5,
  'ratingRecommendation': 'Strong Buy',
  'ratingDetailsDCFScore': 5,
  'ratingDetailsDCFRecommendation': 'Strong Buy',
  'ratingDetailsROEScore': 4,
  'ratingDetailsROERecommendation': 'Buy',
  'ratingDetailsROAScore': 3,
  'ratingDetailsROARecommendation': 'Neutral',
  'ratingDetailsDEScore': 5,
  'ratingDetailsDERecommendation': 'Strong Buy',
  'ratingDetailsPEScore': 5,
  'ratingDetailsPERecommendation': 'Strong Buy',
  'ratingDetailsPBScore': 5,
  'ratingDetailsPBRecommendation': 'Strong Buy'}]

In [101]:
# Company Discounted cash flow value - REAL-TIME
query = search_query_format.format( url, "/api/v3/discounted-cash-flow/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'date': '2020-11-03',
  'dcf': 110.93884618136224,
  'Stock Price': 108.77}]

In [102]:
# Companies Historical Discounted cash flow value
query = search_query_format.format( url, "/api/v3/historical-discounted-cash-flow/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL',
  'historicalDCF': [{'date': '2020-09-26',
    'Stock Price': 115.050003,
    'DCF': 117.21884918136223},
   {'date': '2019-09-28', 'Stock Price': 62.262501, 'DCF': 72.83975431833062},
   {'date': '2018-09-29', 'Stock Price': 53.060001, 'DCF': 58.28927013532511},
   {'date': '2017-09-30', 'Stock Price': 41.68, 'DCF': 45.5688362855317},
   {'date': '2016-09-24', 'Stock Price': 29.4125, 'DCF': 33.15672847032072},
   {'date': '2015-09-26', 'Stock Price': 28.82, 'DCF': 32.49085947647495},
   {'date': '2014-09-27', 'Stock Price': 26.2775, 'DCF': 28.55238886829373},
   {'date': '2013-09-28', 'Stock Price': 18.924286, 'DCF': 34.33390698967829},
   {'date': '2012-09-29', 'Stock Price': 21.571428, 'DCF': 33.066713713368806},
   {'date': '2011-09-24', 'Stock Price': 14.491786, 'DCF': 25.1111152349106},
   {'date': '2010-09-25', 'Stock Price': 11.03, 'DCF': 23.412059263673758},
   {'date': '2009-09-26',
    'Stock Price': 7.231429,
    'DCF': 10.973265675933227}]}]

In [103]:
# Companies DAILY Discounted cash flow value
query = search_query_format.format( url, "/api/v3/historical-daily-discounted-cash-flow/AAPL?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL', 'date': '2020-11-02', 'dcf': 110.93884618136224}]

> There are a lot more functionalities that can be found here: https://financialmodelingprep.com/developer/docs/#Stock-Price

### 2.2 Stock REAL-TIME Price

In [106]:
# Real time stock price
query = query_format.format( url, "/api/v3/quote-short/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'AAPL', 'price': 108.77, 'volume': 122866899}]

In [108]:
# All real-time stock price
query = search_query_format.format( url, "/api/v3/quotes/nyse?limit=1", YOUR_API_KEY )
r = requests.get(query)
r.json()[:2]

[{'symbol': 'NIO',
  'name': 'NIO Limited',
  'price': 33.32,
  'changesPercentage': 8.96,
  'change': 2.74,
  'dayLow': 31.68,
  'dayHigh': 34.94,
  'yearHigh': 34.94,
  'yearLow': 1.66,
  'marketCap': 45387837440.0,
  'priceAvg50': 23.353333,
  'priceAvg200': 13.121439,
  'volume': 265573059,
  'avgVolume': 112395310,
  'exchange': 'NYSE',
  'open': 33.95,
  'previousClose': 30.58,
  'eps': -44.102,
  'pe': None,
  'earningsAnnouncement': '2020-05-28T12:30:00.000+0000',
  'sharesOutstanding': 1362179995,
  'timestamp': 1604409237},
 {'symbol': 'QEMM',
  'name': 'SPDR MSCI Emerging Markets StrategicFactors ETF',
  'price': 57.18,
  'changesPercentage': 1.22,
  'change': 0.687,
  'dayLow': 56.9155,
  'dayHigh': 57.18,
  'yearHigh': 62.18,
  'yearLow': 40.91,
  'marketCap': None,
  'priceAvg50': 57.35389,
  'priceAvg200': 54.67914,
  'volume': 2425,
  'avgVolume': 12183,
  'exchange': 'NYSE',
  'open': 56.9155,
  'previousClose': 56.493,
  'eps': None,
  'pe': None,
  'earningsAnnouncement': None,
  'sharesOutstanding': None,
  'timestamp': 1604409237}]

### 2.3. Stock Historical Price

In [112]:
# 1 minute
query = query_format.format( url, "/api/v3/historical-chart/1min/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()[:4]

[{'date': '2020-11-02 16:00:00',
  'open': 108.42,
  'low': 108.41,
  'high': 108.55,
  'close': 108.55,
  'volume': 113655901},
 {'date': '2020-11-02 15:59:00',
  'open': 108.695,
  'low': 108.42,
  'high': 108.695,
  'close': 108.42,
  'volume': 112400960},
 {'date': '2020-11-02 15:58:00',
  'open': 108.64,
  'low': 108.64,
  'high': 108.6973,
  'close': 108.695,
  'volume': 111531090},
 {'date': '2020-11-02 15:57:00',
  'open': 108.595,
  'low': 108.575,
  'high': 108.66,
  'close': 108.64,
  'volume': 110909010}]

In [113]:
# 5 minute
query = query_format.format( url, "/api/v3/historical-chart/5min/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()[:4]

[{'date': '2020-11-02 16:00:00',
  'open': 108.081,
  'low': 108.081,
  'high': 108.6973,
  'close': 108.55,
  'volume': 113655901},
 {'date': '2020-11-02 15:55:00',
  'open': 108.105,
  'low': 107.965,
  'high': 108.22,
  'close': 108.081,
  'volume': 109293284},
 {'date': '2020-11-02 15:50:00',
  'open': 107.82,
  'low': 107.8,
  'high': 108.15,
  'close': 108.105,
  'volume': 106999825},
 {'date': '2020-11-02 15:45:00',
  'open': 107.9938,
  'low': 107.82,
  'high': 108.025,
  'close': 107.82,
  'volume': 105367869}]

In [114]:
# 15 minute
query = query_format.format( url, "/api/v3/historical-chart/15min/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()[:4]

[{'date': '2020-11-02 16:00:00',
  'open': 107.82,
  'low': 107.8,
  'high': 108.6973,
  'close': 108.55,
  'volume': 113655901},
 {'date': '2020-11-02 15:45:00',
  'open': 108.215,
  'low': 107.82,
  'high': 108.37,
  'close': 107.82,
  'volume': 105367869},
 {'date': '2020-11-02 15:30:00',
  'open': 107.99,
  'low': 107.99,
  'high': 108.31,
  'close': 108.215,
  'volume': 101411064},
 {'date': '2020-11-02 15:15:00',
  'open': 107.77,
  'low': 107.765,
  'high': 108.0799,
  'close': 107.99,
  'volume': 98305122}]

In [115]:
# 30 minute
query = query_format.format( url, "/api/v3/historical-chart/30min/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()[:4]

[{'date': '2020-11-02 16:00:00',
  'open': 108.215,
  'low': 107.8,
  'high': 108.6973,
  'close': 108.55,
  'volume': 113655901},
 {'date': '2020-11-02 15:30:00',
  'open': 107.77,
  'low': 107.765,
  'high': 108.31,
  'close': 108.215,
  'volume': 101411064},
 {'date': '2020-11-02 15:00:00',
  'open': 107.6362,
  'low': 107.6,
  'high': 107.77,
  'close': 107.77,
  'volume': 95522073},
 {'date': '2020-11-02 14:30:00',
  'open': 107.4,
  'low': 107.37,
  'high': 107.894,
  'close': 107.7738,
  'volume': 90043567}]

In [116]:
# 1 hour
query = query_format.format( url, "/api/v3/historical-chart/1hour/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()[:4]

[{'date': '2020-11-02 16:00:00',
  'open': 107.77,
  'low': 107.765,
  'high': 108.6973,
  'close': 108.55,
  'volume': 113655901},
 {'date': '2020-11-02 15:00:00',
  'open': 107.6362,
  'low': 107.6,
  'high': 107.77,
  'close': 107.77,
  'volume': 95522073},
 {'date': '2020-11-02 14:00:00',
  'open': 108.035,
  'low': 107.34,
  'high': 108.18,
  'close': 107.4,
  'volume': 83885327},
 {'date': '2020-11-02 13:00:00',
  'open': 108.44,
  'low': 107.8253,
  'high': 108.5,
  'close': 108.13,
  'volume': 71650963}]

In [119]:
# 4 hours
query = query_format.format( url, "/api/v3/historical-chart/4hour/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()[:4]

[{'date': '2020-11-02 16:00:00',
  'open': 107.6362,
  'low': 107.6,
  'high': 108.6973,
  'close': 108.55,
  'volume': 113655901},
 {'date': '2020-11-02 12:00:00',
  'open': 107.915,
  'low': 107.7335,
  'high': 108.33,
  'close': 107.98,
  'volume': 57998498},
 {'date': '2020-10-30 16:00:00',
  'open': 108.26,
  'low': 108.19,
  'high': 109.1,
  'close': 109.1,
  'volume': 173440278},
 {'date': '2020-10-30 12:00:00',
  'open': 109.6266,
  'low': 108.7501,
  'high': 109.67,
  'close': 108.7699,
  'volume': 89705893}]

In [ ]:
# Historical Daily Prices
query = search_query_format.format( url, "/api/v3/historical-price-full/AAPL?serietype=line", YOUR_API_KEY )
r = requests.get(query)
r.json()

In [ ]:
# Historical Daily Prices with change and volume
query = query_format.format( url, "/api/v3/historical-price-full/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()

In [127]:
# Historical Daily Prices with change and volume interval
query = search_query_format.format( url, "/api/v3/historical-price-full/AAPL?from=2019-03-11&to=2019-03-12", YOUR_API_KEY )
r = requests.get(query)
r.json()

{'symbol': 'AAPL',
 'historical': [{'date': '2019-03-12',
   'open': 45.0,
   'high': 45.6675,
   'low': 44.842499,
   'close': 45.227501,
   'adjClose': 44.442513,
   'volume': 129870400.0,
   'unadjustedVolume': 129870400.0,
   'change': 0.2275,
   'changePercent': 0.506,
   'vwap': 45.24583,
   'label': 'March 12, 19',
   'changeOverTime': 0.00506},
  {'date': '2019-03-11',
   'open': 43.872501,
   'high': 44.779999,
   'low': 43.837502,
   'close': 44.724998,
   'adjClose': 43.94873,
   'volume': 128044000.0,
   'unadjustedVolume': 128044000.0,
   'change': 0.8525,
   'changePercent': 1.943,
   'vwap': 44.4475,
   'label': 'March 11, 19',
   'changeOverTime': 0.01943}]}

In [128]:
# Historical Daily Prices with change and volume Time series
query = search_query_format.format( url, "/api/v3/historical-price-full/AAPL?timeseries=5", YOUR_API_KEY )
r = requests.get(query)
r.json()

{'symbol': 'AAPL',
 'historical': [{'date': '2020-11-02',
   'open': 109.11,
   'high': 110.68,
   'low': 107.32,
   'close': 108.77,
   'adjClose': 108.77,
   'volume': 122866899.0,
   'unadjustedVolume': 122866899.0,
   'change': -0.34,
   'changePercent': -0.312,
   'vwap': 108.92333,
   'label': 'November 02, 20',
   'changeOverTime': -0.00312},
  {'date': '2020-10-30',
   'open': 111.059998,
   'high': 111.989998,
   'low': 107.720001,
   'close': 108.860001,
   'adjClose': 108.860001,
   'volume': 190272600.0,
   'unadjustedVolume': 190272600.0,
   'change': -2.2,
   'changePercent': -1.981,
   'vwap': 109.52333,
   'label': 'October 30, 20',
   'changeOverTime': -0.01981},
  {'date': '2020-10-29',
   'open': 112.370003,
   'high': 116.93,
   'low': 112.199997,
   'close': 115.32,
   'adjClose': 115.32,
   'volume': 146129200.0,
   'unadjustedVolume': 146129200.0,
   'change': 2.95,
   'changePercent': 2.625,
   'vwap': 114.81667,
   'label': 'October 29, 20',
   'changeOverTime': 0.02625},
  {'date': '2020-10-28',
   'open': 115.050003,
   'high': 115.43,
   'low': 111.099998,
   'close': 111.199997,
   'adjClose': 111.199997,
   'volume': 143937800.0,
   'unadjustedVolume': 143937800.0,
   'change': -3.85001,
   'changePercent': -3.346,
   'vwap': 112.57667,
   'label': 'October 28, 20',
   'changeOverTime': -0.03346},
  {'date': '2020-10-27',
   'open': 115.489998,
   'high': 117.279999,
   'low': 114.540001,
   'close': 116.599998,
   'adjClose': 116.599998,
   'volume': 92276800.0,
   'unadjustedVolume': 92276800.0,
   'change': 1.11,
   'changePercent': 0.961,
   'vwap': 116.14,
   'label': 'October 27, 20',
   'changeOverTime': 0.00961}]}

In [ ]:
# BATCH REQUEST STOCK DAILY HISTORICAL PRICE
query = query_format.format( url, "/api/v3/historical-price-full/AAPL,GOOG,FB", YOUR_API_KEY )
r = requests.get(query)
r.json()

### 2.4. Historical Dividends

In [ ]:
# Stock Daily historical dividend prices
query = query_format.format( url, "/api/v3/historical-price-full/stock_dividend/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()

# Stock Daily historical splits
query = query_format.format( url, "/api/v3/historical-price-full/stock_split/AAPL", YOUR_API_KEY )
r = requests.get(query)
r.json()

### 2.5 Technical Indicators

Type: SMA - EMA - WMA - DEMA - TEMA - williams - RSI - ADX - standardDeviation

In [139]:
# Daily Indicators
query = search_query_format.format( url, "/api/v3/technical_indicator/daily/AAPL?period=10&tipe=ema", YOUR_API_KEY )
r = requests.get(query)
r.json()[:2]

[{'date': '2020-11-02',
  'open': 109.11,
  'high': 110.68,
  'low': 107.32,
  'close': 108.77,
  'volume': 122866899.0,
  'sma': 114.0970005},
 {'date': '2020-10-30',
  'open': 111.059998,
  'high': 111.989998,
  'low': 107.720001,
  'close': 108.860001,
  'volume': 190272600.0,
  'sma': 114.8180008}]

In [141]:
# Intraday Indicators

# 1 min
query = search_query_format.format( url, "/api/v3/technical_indicator/1min/AAPL?period=10&tipe=ema", YOUR_API_KEY )
r = requests.get(query)
r.json()[:2]

[{'date': '2020-11-02 16:00:00',
  'open': 108.081,
  'high': 108.6973,
  'low': 108.081,
  'close': 108.55,
  'volume': 113655901.0,
  'sma': 108.11127},
 {'date': '2020-11-02 15:55:00',
  'open': 108.105,
  'high': 108.22,
  'low': 107.965,
  'close': 108.081,
  'volume': 109293284.0,
  'sma': 108.04227}]

In [142]:
# 5min 
query = search_query_format.format( url, "/api/v3/technical_indicator/5min/AAPL?period=10&tipe=ema", YOUR_API_KEY )
r = requests.get(query)
r.json()[:2]

# ...

[{'date': '2020-11-02 16:00:00',
  'open': 108.081,
  'high': 108.6973,
  'low': 108.081,
  'close': 108.55,
  'volume': 113655901.0,
  'sma': 108.11127},
 {'date': '2020-11-02 15:55:00',
  'open': 108.105,
  'high': 108.22,
  'low': 107.965,
  'close': 108.081,
  'volume': 109293284.0,
  'sma': 108.04227}]

### 2.6 Market Indexes

In [143]:
query = query_format.format( url, "/api/v3/quotes/index", YOUR_API_KEY )
r = requests.get(query)
r.json()[:2]

[{'symbol': '^IBEX',
  'name': 'IBEX 35',
  'price': 6701.5,
  'changesPercentage': 1.76,
  'change': 115.9,
  'dayLow': 6608.7,
  'dayHigh': 6707.2,
  'yearHigh': 10100.2,
  'yearLow': 5814.5,
  'marketCap': None,
  'priceAvg50': 6799.6113,
  'priceAvg200': 7036.881,
  'volume': 123566211,
  'avgVolume': 232675731,
  'exchange': 'INDEX',
  'open': 6636.1,
  'previousClose': 6585.6,
  'eps': None,
  'pe': None,
  'earningsAnnouncement': None,
  'sharesOutstanding': None,
  'timestamp': 1604410402},
 {'symbol': '^MXX',
  'name': 'IPC MEXICO',
  'price': 36987.86,
  'changesPercentage': 0.51,
  'change': 186.49,
  'dayLow': 0.0,
  'dayHigh': 0.0,
  'yearHigh': 45955.41,
  'yearLow': 0.0,
  'marketCap': None,
  'priceAvg50': 37312.555,
  'priceAvg200': 37196.184,
  'volume': 0,
  'avgVolume': 154530578,
  'exchange': 'INDEX',
  'open': 0.0,
  'previousClose': 36801.37,
  'eps': None,
  'pe': None,
  'earningsAnnouncement': None,
  'sharesOutstanding': None,
  'timestamp': 1604410402}]

### 2.7. Stock Market

In [147]:
## MOST ACTIVES STOCK COMPANIES
query = query_format.format( url, "/api/v3/actives", YOUR_API_KEY )
r = requests.get(query)
r.json()[:3]

[{'ticker': 'BRK-A',
  'changes': 3875.0,
  'price': '306375',
  'changesPercentage': '(+1.28%)',
  'companyName': 'Berkshire Hathaway Inc'},
 {'ticker': 'NVR',
  'changes': 76.18,
  'price': '4029.27',
  'changesPercentage': '(+1.93%)',
  'companyName': 'NVR Inc'},
 {'ticker': 'MTD',
  'changes': 45.34,
  'price': '1043.25',
  'changesPercentage': '(+4.54%)',
  'companyName': 'Mettler-Toledo International Inc'}]

In [148]:
## MOST GAINER STOCK COMPANIES
query = query_format.format( url, "/api/v3/gainers", YOUR_API_KEY )
r = requests.get(query)
r.json()[:3]

[{'ticker': 'EIGI',
  'changes': 3.6,
  'price': '9.41',
  'changesPercentage': '(+61.96%)',
  'companyName': 'Endurance International Group Holdings Inc'},
 {'ticker': 'SUP',
  'changes': 0.74,
  'price': '1.97',
  'changesPercentage': '(+60.16%)',
  'companyName': 'Superior Industries International Inc'},
 {'ticker': 'DGLY',
  'changes': 0.75,
  'price': '3.04',
  'changesPercentage': '(+32.75%)',
  'companyName': 'Digital Ally Inc'}]

In [149]:
## MOST LOSER STOCK COMPANIES
query = query_format.format( url, "/api/v3/losers", YOUR_API_KEY )
r = requests.get(query)
r.json()[:3]

[{'ticker': 'MICT',
  'changes': -1.32,
  'price': '1.8',
  'changesPercentage': '(-42.31%)',
  'companyName': 'MICT Inc'},
 {'ticker': 'LQDA',
  'changes': -1.28,
  'price': '3.34',
  'changesPercentage': '(-27.71%)',
  'companyName': 'Liquidia Technologies Inc'},
 {'ticker': 'WINS',
  'changes': -4.09,
  'price': '14.21',
  'changesPercentage': '(-22.35%)',
  'companyName': 'Wins Finance Holdings Inc'}]

### 2.8. Cryptocurrencies Price

In [150]:
## 4 HOURS HISTORICAL STOCK PRICES WITH VOLUME
query = query_format.format( url, "/api/v3/historical-chart/4hour/BTCUSD", YOUR_API_KEY )
r = requests.get(query)
r.json()[:3]

[{'date': '2020-11-03 08:00:00',
  'open': 13503.063,
  'low': 13481.401,
  'high': 13509.249,
  'close': 13509.249,
  'volume': 29803030528},
 {'date': '2020-11-03 04:00:00',
  'open': 13508.853,
  'low': 13508.218,
  'high': 13537.234,
  'close': 13515.623,
  'volume': 31776024576},
 {'date': '2020-11-03 00:00:00',
  'open': 13347.528,
  'low': 13340.728,
  'high': 13435.195,
  'close': 13431.476,
  'volume': 31214485504}]

### 2.9. FOREX

In [151]:
## Currency exchange rates (FX)
query = query_format.format( url, "/api/v3/fx", YOUR_API_KEY )
r = requests.get(query)
r.json()[:3]

[{'ticker': 'EUR/USD',
  'bid': '1.17103',
  'ask': '1.17103',
  'open': '1.16387',
  'low': '1.16236',
  'high': '1.17181',
  'changes': 0.6151889815872954,
  'date': '2020-11-03 08:40:17'},
 {'ticker': 'USD/JPY',
  'bid': '104.67100000',
  'ask': '104.67100000',
  'open': '104.711',
  'low': '104.480',
  'high': '104.806',
  'changes': -0.038200380093774335,
  'date': '2020-11-03 08:40:17'},
 {'ticker': 'GBP/USD',
  'bid': '1.30072',
  'ask': '1.30072',
  'open': '1.29169',
  'low': '1.29107',
  'high': '1.30116501',
  'changes': 0.6990841455767324,
  'date': '2020-11-03 08:40:17'}]

In [152]:
## All Real-time Forex Prices
query = query_format.format( url, "/api/v3/quotes/forex", YOUR_API_KEY )
r = requests.get(query)
r.json()[:3]

[{'symbol': 'CHFNZD',
  'name': 'CHF/NZD',
  'price': 1.637,
  'changesPercentage': -0.28,
  'change': -0.0046,
  'dayLow': 1.6333,
  'dayHigh': 1.6433,
  'yearHigh': 1.88382,
  'yearLow': 1.5259,
  'marketCap': None,
  'priceAvg50': 1.646178,
  'priceAvg200': 1.6545722,
  'volume': 0,
  'avgVolume': 0,
  'exchange': 'FOREX',
  'open': 1.642,
  'previousClose': 1.6416,
  'eps': None,
  'pe': None,
  'earningsAnnouncement': None,
  'sharesOutstanding': None,
  'timestamp': 1604410859},
 {'symbol': 'AUDHKD',
  'name': 'AUD/HKD',
  'price': 5.5288,
  'changesPercentage': 1.2,
  'change': 0.0656,
  'dayLow': 5.4335,
  'dayHigh': 5.5338,
  'yearHigh': 5.74338,
  'yearLow': 4.28482,
  'marketCap': None,
  'priceAvg50': 5.539083,
  'priceAvg200': 5.3885846,
  'volume': 0,
  'avgVolume': 0,
  'exchange': 'FOREX',
  'open': 5.4632,
  'previousClose': 5.4632,
  'eps': None,
  'pe': None,
  'earningsAnnouncement': None,
  'sharesOutstanding': None,
  'timestamp': 1604410859},
 {'symbol': 'CADAUD',
  'name': 'CAD/AUD',
  'price': 1.0658,
  'changesPercentage': -0.54,
  'change': -0.0058,
  'dayLow': 1.0644,
  'dayHigh': 1.0747,
  'yearHigh': 1.23551,
  'yearLow': 1.03119,
  'marketCap': None,
  'priceAvg50': 1.0570095,
  'priceAvg200': 1.0671606,
  'volume': 0,
  'avgVolume': 0,
  'exchange': 'FOREX',
  'open': 1.0717,
  'previousClose': 1.0716,
  'eps': None,
  'pe': None,
  'earningsAnnouncement': None,
  'sharesOutstanding': None,
  'timestamp': 1604410859}]

In [155]:
## Single CURRENCY
query = query_format.format( url, "/api/v3/fx/EURUSD", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'ticker': 'EUR/USD',
  'bid': '1.171185',
  'ask': '1.171185',
  'open': '1.16387',
  'low': '1.16236',
  'high': '1.17181',
  'changes': 0.6285066201551686,
  'date': '2020-11-03 08:41:38'}]

In [156]:
## Real-time Forex Price
query = query_format.format( url, "/api/v3/quote/JPYUSD", YOUR_API_KEY )
r = requests.get(query)
r.json()

[{'symbol': 'JPYUSD',
  'name': 'JPY/USD',
  'price': 0.00955192,
  'changesPercentage': 0.03,
  'change': 2.64e-06,
  'dayLow': 0.0095418,
  'dayHigh': 0.00957488,
  'yearHigh': 0.00987333,
  'yearLow': 0.00891377,
  'marketCap': None,
  'priceAvg50': 0.00950498,
  'priceAvg200': 0.00939211,
  'volume': 0,
  'avgVolume': 0,
  'exchange': 'FOREX',
  'open': 0.00954891,
  'previousClose': 0.00954927,
  'eps': None,
  'pe': None,
  'earningsAnnouncement': None,
  'sharesOutstanding': None,
  'timestamp': 1604410913}]